"""표 만들기

Revision ID: 22ca2bd6998f
Revises: 
Create Date: 2026-08-28 13:37:52.630298
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '22ca2bd6998f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ministry', sa.String(length=120), nullable=False),
    sa.Column('agency', sa.String(length=200), nullable=False),
    sa.Column('no', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('program', sa.String(length=300), nullable=False),
    sa.Column('posted', sa.Date(), nullable=True),
    sa.Column('open_from', sa.Date(), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('due_time', sa.String(length=5), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_due'), ['due'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_ministry'), ['ministry'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_posted'), ['posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_url'), ['url'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('collector_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('total_seen', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('agency', sa.String(length=300), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('budget', sa.BigInteger(), nullable=False),
    sa.Column('cycle', sa.String(length=10), nullable=False),
    sa.Column('folder_url', sa.Text(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_favorites',
    sa.Column('announcement_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_table('project_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('budget_amount', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_category_per_project')
    )
    with op.batch_alter_table('project_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_categories_project_id'), ['project_id'], unique=False)

    op.create_table('project_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_kpi_per_project')
    )
    with op.batch_alter_table('project_kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_kpis_project_id'), ['project_id'], unique=False)

    op.create_table('project_stage_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'stage_index', name='uq_stage_note_per_project')
    )
    with op.batch_alter_table('project_stage_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_stage_notes_project_id'), ['project_id'], unique=False)

    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('project_todos',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_todos_project_id'), ['project_id'], unique=False)

    op.create_table('report_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('act', sa.Text(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('issue_done', sa.Boolean(), nullable=False),
    sa.Column('entered_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'period_key', name='uq_entry_per_period')
    )
    with op.batch_alter_table('report_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_entries_project_id'), ['project_id'], unique=False)

    op.create_table('entry_kpi_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('kpi_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['report_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'kpi_name', name='uq_kpi_value_per_entry')
    )
    with op.batch_alter_table('entry_kpi_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_kpi_values_entry_id'), ['entry_id'], unique=False)

    op.create_table('entry_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.String(length=60), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['report_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'revision_no', name='uq_revision_per_entry')
    )
    with op.batch_alter_table('entry_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_revisions_entry_id'), ['entry_id'], unique=False)

    op.create_table('entry_spends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['report_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry_spends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_spends_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_spends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_spends_entry_id'))

    op.drop_table('entry_spends')
    with op.batch_alter_table('entry_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_revisions_entry_id'))

    op.drop_table('entry_revisions')
    with op.batch_alter_table('entry_kpi_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_kpi_values_entry_id'))

    op.drop_table('entry_kpi_values')
    with op.batch_alter_table('report_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_entries_project_id'))

    op.drop_table('report_entries')
    with op.batch_alter_table('project_todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_todos_project_id'))

    op.drop_table('project_todos')
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tasks_project_id'))

    op.drop_table('project_tasks')
    with op.batch_alter_table('project_stage_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_stage_notes_project_id'))

    op.drop_table('project_stage_notes')
    with op.batch_alter_table('project_kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_kpis_project_id'))

    op.drop_table('project_kpis')
    with op.batch_alter_table('project_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_categories_project_id'))

    op.drop_table('project_categories')
    op.drop_table('announcement_favorites')
    op.drop_table('projects')
    op.drop_table('collector_runs')
    op.drop_table('app_settings')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_url'))
        batch_op.drop_index(batch_op.f('ix_announcements_source'))
        batch_op.drop_index(batch_op.f('ix_announcements_posted'))
        batch_op.drop_index(batch_op.f('ix_announcements_ministry'))
        batch_op.drop_index(batch_op.f('ix_announcements_due'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
