"""성과지표 소수점 허용

Revision ID: 7873989df1fe
Revises: 3d729a105775
Create Date: 2026-08-28 16:11:02.960388
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7873989df1fe'
down_revision = '3d729a105775'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_kpi_values', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('project_kpis', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_kpis', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('entry_kpi_values', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
