"""add meetings

Revision ID: d73250fd265f
Revises: cac0640bbf29
Create Date: 2026-09-08 09:24:00.906491
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd73250fd265f'
down_revision = 'cac0640bbf29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('met_on', sa.Date(), nullable=False),
    sa.Column('place', sa.String(length=120), nullable=False),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('bullets', sa.JSON(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_meetings_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_project_id'), ['project_id'], unique=False)

    op.create_table('meeting_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('stored_name', sa.String(length=120), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_photos_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_photos'))
    )
    with op.batch_alter_table('meeting_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_photos_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_photos_meeting_id'))

    op.drop_table('meeting_photos')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_project_id'))

    op.drop_table('meetings')
    # ### end Alembic commands ###
