"""add reviews

Revision ID: ed0b89894a75
Revises: d73250fd265f
Create Date: 2026-09-08 20:31:27.999182
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ed0b89894a75'
down_revision = 'd73250fd265f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('agency', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('announcement_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_announcement_id'), ['announcement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_announcement_id'))

    op.drop_table('reviews')
    # ### end Alembic commands ###
